import { z } from "zod";

export const PlanInputSchema = z.object({
    learnerType: z.string().min(1),
    background: z.string().min(1),
    goal: z.string().min(1),
    careerOutcome: z.string().min(1),
    availability: z.string().min(1),
    learningPreference: z.string().min(1),
    realWorldApp: z.union([z.array(z.string()), z.string()]),
    experience: z.object({
        python: z.boolean(),
        sql: z.boolean(),
        statistics: z.boolean(),
        ml: z.boolean(),
        dl: z.boolean(),
        nlp: z.boolean(),
        genai: z.boolean(),
        mlops: z.boolean(),
        excel_bi: z.boolean(),
        data_engineering: z.boolean(),
        big_data: z.boolean(),
    }),
    syllabusChapters: z.array(z.object({
        id: z.string(),
        title: z.string(),
        subjectId: z.string(),
        topics: z.array(z.string()),
        durationWeeks: z.number(),
        isProject: z.boolean().optional(),
        isInternship: z.boolean().optional(),
        resources: z.array(z.object({ label: z.string(), url: z.string() })).optional(),
    })).min(1),
    syllabusSubjects: z.array(z.object({
        id: z.string(),
        name: z.string(),
        displayName: z.string(),
        color: z.string(),
        category: z.enum(["foundation", "core-ai", "specialization", "career"]),
        chapterIds: z.array(z.string()),
        tags: z.object({ category: z.string(), level: z.string() }).optional(),
    })),
    hasPythonBasics: z.boolean().optional(),
    hasgitBasics: z.boolean().optional(),
    hasDSABasics: z.boolean().optional(),
    hasAIIntro: z.boolean().optional(),
});
